### ISSUE TITLE
HW#2 Improvements

### ISSUE THREAD

**Issue by dklein3** [dklein3/CLIM680#2]
I would like to increase the font size on the units (mm) on the colorbar. 

I used a 20x20 figure size. I think this would be fine for a poster presentation. For a journal, I believe I could resize it as a png or jpg, rather than trying to get the fonts and spacing right in a smaller size.

**Comment by nburls** [comment]
Try cbar.set_label(size=12) or cbar.set_label('mm',size=12)

Journals typically want vector format like eps which helps with resizing.

**Comment by pdirmeyer** [comment]
Redefining the month coordinate with month names was a nice touch - `groupby` tends to clobber the time coordinate.
